export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CLIENTS_REPOSITORY = 'CLIENTS_REPOSITORY';
export const PASSWORD_HASHER = 'PASSWORD_HASHER';
export const AUTH_DOMAIN_SERVICE = 'AUTH_DOMAIN_SERVICE';
export const CLIENTS_DOMAIN_SERVICE = 'CLIENTS_DOMAIN_SERVICE';
export const DATABASE_SOURCE = 'DATABASE_SOURCE';